### ISSUE TITLE
Media object example is below the flag object

### ISSUE THREAD

**Issue by alexcarpenter** [charliewilco/obsidian#37]
https://github.com/charliewilco/obsidian/blob/deb684ce57f1933734851ec513a11280042b3e00/documentation/markdown/objects/flag.mdx#L4

**Comment by charliewilco** [comment]
https://github.com/charliewilco/obsidian/blob/deb684ce57f1933734851ec513a11280042b3e00/documentation/pages/objects.js#L27

so in this page, you can just swap the order of the `<Module />` components
